# GNU GCC toolchain
include_guard(GLOBAL)

cmake_minimum_required(VERSION 3.28 FATAL_ERROR)

set(CMAKE_SYSTEM_NAME Linux CACHE STRING "")

include(${CMAKE_CURRENT_LIST_DIR}/../common-toolchain.cmake)

set(CMAKE_CXX_COMPILER "g++")
set(CMAKE_C_COMPILER "gcc")
set(ENV{CC} "gcc")
set(ENV{CXX} "g++")

list(APPEND TC_BASE_C_FLAGS -Wno-builtin-macro-redefined)
list(APPEND TC_BASE_CXX_FLAGS -Wno-builtin-macro-redefined)

link_libraries(stdc++exp)

include(${CMAKE_CURRENT_LIST_DIR}/../../Features/SanitizersLinux.cmake)
set(SANITIZER_FLAGS_LIST "")
get_sanitizers_flags_linux(SANITIZER_FLAGS_LIST)

list(APPEND TC_BASE_C_FLAGS ${SANITIZER_FLAGS_LIST})
list(APPEND TC_BASE_CXX_FLAGS ${SANITIZER_FLAGS_LIST})
list(APPEND TC_BASE_SHARED_LINKER_FLAGS ${SANITIZER_FLAGS_LIST})
list(APPEND TC_BASE_EXE_LINKER_FLAGS ${SANITIZER_FLAGS_LIST})
list(APPEND TC_BASE_MODULE_LINKER_FLAGS ${SANITIZER_FLAGS_LIST})

set(VCPKG_TARGET_TRIPLET "x64-linux-gcc-sanitizers" CACHE STRING "Vcpkg target triplet")

list(JOIN TC_BASE_C_FLAGS " " TC_BASE_C_FLAGS_STRING)
set(CMAKE_C_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} ${TC_BASE_C_FLAGS_STRING}")

list(JOIN TC_BASE_CXX_FLAGS " " TC_BASE_CXX_FLAGS_STRING)
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} ${TC_BASE_CXX_FLAGS_STRING}")

list(JOIN TC_BASE_SHARED_LINKER_FLAGS " " TC_BASE_SHARED_LINKER_FLAGS_STRING)
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${CMAKE_SHARED_LINKER_FLAGS_INIT} ${TC_BASE_SHARED_LINKER_FLAGS_STRING}")

list(JOIN TC_BASE_EXE_LINKER_FLAGS " " TC_BASE_EXE_LINKER_FLAGS_STRING)
set(CMAKE_EXE_LINKER_FLAGS_INIT "${CMAKE_EXE_LINKER_FLAGS_INIT} ${TC_BASE_EXE_LINKER_FLAGS_STRING}")

list(JOIN TC_BASE_MODULE_LINKER_FLAGS " " TC_BASE_MODULE_LINKER_FLAGS_STRING)
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${CMAKE_MODULE_LINKER_FLAGS_INIT} ${TC_BASE_MODULE_LINKER_FLAGS_STRING}")

include(${CMAKE_CURRENT_LIST_DIR}/../vcpkg-toolchain.cmake)
