
name: 'vcpkg_cache'
description: 'Sets up the vcpkg cache using NuGet and GitHub Packages'

inputs:
  token:
    description: 'The GitHub token to use for authentication with the NuGet source'
    required: true

runs:
  using: "composite"
  steps:
  - name: Setup NuGet for GitHub Packages (Windows)
    if: runner.os == 'Windows'
    shell: pwsh
    run: |
      $vcpkgExe = "$env:VCPKG_INSTALLATION_ROOT\vcpkg.exe"
      $feedUrl = "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      
      # Use vcpkg to fetch nuget.exe
      $nuget = & $vcpkgExe fetch nuget | Out-String | ForEach-Object { $_.Trim() } | Select-Object -Last 1
      
      # Add the NuGet source if it doesn't exist
      & $nuget sources add -Source "$feedUrl" -StorePasswordInClearText -Name GitHub -UserName "${{ github.repository_owner }}" -Password "${{ inputs.token }}" 2>$null || echo "Source 'GitHub' already exists"
      
      # Set the API key for the source
      & $nuget setapikey "${{ inputs.token }}" -Source "$feedUrl"

  - name: Setup NuGet for GitHub Packages (Linux)
    if: runner.os == 'Linux'
    shell: bash
    run: |
      # Install leanest mono possible for running nuget.exe
      if ! command -v mono &> /dev/null; then
        apt-get update
        apt-get install -y --no-install-recommends mono-runtime ca-certificates-mono
      fi

      vcpkg_exe="$VCPKG_INSTALLATION_ROOT/vcpkg"
      feed_url="https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      
      # Use vcpkg to fetch nuget.exe
      nuget_path=$($vcpkg_exe fetch nuget | tail -n 1)
      
      # Add the NuGet source
      mono "$nuget_path" sources add \
        -Source "$feed_url" \
        -StorePasswordInClearText \
        -Name GitHub \
        -UserName "${{ github.repository_owner }}" \
        -Password "${{ inputs.token }}" || echo "Source 'GitHub' already exists"
      
      # Set the API key
      mono "$nuget_path" setapikey "${{ inputs.token }}" -Source "$feed_url"

  - name: Export vcpkg binary sources
    shell: bash
    run: |
      # Configure vcpkg to use the 'GitHub' NuGet source
      echo "VCPKG_BINARY_SOURCES=clear;nuget,GitHub,readwrite" >> $GITHUB_ENV
