
name: 'vcpkg_cache'
description: 'Sets up the vcpkg cache'

# env: 
#     VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

runs:
  using: "composite"
  steps:
  - name: Export GitHub Actions cache environment variables
    uses: actions/github-script@v7
    with:
      script: |
        core.exportVariable('VCPKG_BINARY_SOURCES', "clear;x-gha,readwrite" || '');
        core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
        core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

