name: 'vcpkg_cache'
description: 'Sets up the vcpkg cache'

inputs:
  token:
    description: 'The GitHub token to use for authentication with the NuGet source'
    required: true

runs:
  using: "composite"
  steps:
  - name: Setup NuGet for GitHub Packages (Windows)
    if: runner.os == 'Windows'
    shell: pwsh
    run: |
      $feedUrl = "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      dotnet nuget add source "$feedUrl" --name "GitHubPackages" --username "${{ github.repository_owner }}" --password "${{ inputs.token }}" --store-password-in-clear-text || echo "Source already exists"
      dotnet nuget setapikey "${{ inputs.token }}" --source "GitHubPackages"

  - name: Setup NuGet for GitHub Packages (Linux)
    if: runner.os == 'Linux'
    shell: bash
    run: |
      feed_url="https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      
      dotnet nuget add source "$feed_url" \
        --name "GitHubPackages" \
        --username "${{ github.repository_owner }}" \
        --password "${{ inputs.token }}" \
        --store-password-in-clear-text || true
      dotnet nuget setapikey "${{ inputs.token }}" --source "GitHubPackages"

  - name: Export vcpkg binary sources
    shell: bash
    run: |
      echo "VCPKG_BINARY_SOURCES=clear;nuget,GitHubPackages,readwrite" >> $GITHUB_ENV
