set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_ENV_PASSTHROUGH "BUILD_SANITIZER")
set(BUILD_SANITIZER "$ENV{BUILD_SANITIZER}")
include("${CMAKE_CURRENT_LIST_DIR}/../../CMake/Features/SanitizersMsvc.cmake")


include(CMakePrintHelpers)
cmake_print_variables(BUILD_SANITIZER)
cmake_print_variables(SANITIZER_FLAGS)

string(APPEND VCPKG_C_FLAGS "${SANITIZER_FLAGS}")
string(APPEND VCPKG_CXX_FLAGS "${SANITIZER_FLAGS}")
