if(target_sources_included)
    return()
endif()
set(target_sources_included true)


function(add_target_sources TARGETNAME)
  set(options)
  set(oneValueArgs MAINTESTFILE MAINBENCHMARKFILE)
  set(multiValueArgs TESTFILES BENCHMARKFILES MODULEFILES HEADERUNITFILES PRIVATEFILES PUBLICFILES INTERFACEFILES)

  cmake_parse_arguments(PARSE_ARGV 1 ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" )

  #message(STATUS "function=${CMAKE_CURRENT_FUNCTION}")
  #message(STATUS "ARGV=${ARGV}")
  #message(STATUS "ARGN=${ARGN}")
  #message(STATUS "TARGETNAME=${TARGETNAME}")
  #message(STATUS "MAINTESTFILE=${ARG_MAINTESTFILE}")
  #message(STATUS "MAINBENCHMARKFILE=${ARG_MAINBENCHMARKFILE}")
  #message(STATUS "TESTFILES=${ARG_TESTFILES}")
  #message(STATUS "BENCHMARKFILES=${ARG_BENCHMARKFILES}")
  #message(STATUS "MODULEFILES=${ARG_MODULEFILES}")
  #message(STATUS "HEADERUNITFILES=${ARG_HEADERUNITFILES}")
  #message(STATUS "PRIVATEFILES=${ARG_PRIVATEFILES}")
  #message(STATUS "PUBLICFILES=${ARG_PUBLICFILES}")
  #message(STATUS "INTERFACEFILES=${ARG_INTERFACEFILES}")
  #message(STATUS "UNPARSED_ARGUMENTS=${ARG_PREFIX_UNPARSED_ARGUMENTS}")
  #message(STATUS "KEYWORDS_MISSING_VALUES=${ARG_KEYWORDS_MISSING_VALUES}")

  if(CMAKE_VERSION GREATER_EQUAL "3.26.0" )
    target_sources(${TARGETNAME}
      PRIVATE
        ${ARG_PRIVATEFILES}
      PUBLIC
       FILE_SET CXX_MODULES FILES ${ARG_MODULEFILES}
      #PUBLIC
       #FILE_SET CXX_MODULE_HEADER_UNITS FILES ${ARG_HEADERUNITFILES}
      PUBLIC
        ${ARG_PUBLICFILES}
      INTERFACE
        ${ARG_INTERFACEFILES}
    )
  else()
    target_sources(${TARGETNAME}
      PRIVATE
        ${ARG_PRIVATEFILES}
        ${ARG_MODULEFILES}
      #PUBLIC
       #FILE_SET CXX_MODULE_HEADER_UNITS FILES ${ARG_HEADERUNITFILES}
      PUBLIC
        ${ARG_PUBLICFILES}
        ${ARG_HEADERUNITFILES}
      INTERFACE
        ${ARG_INTERFACEFILES}
    )
  endif()

  if(BUILD_TESTS AND ARG_TESTFILES )
    add_test_target_sources( ${TARGETNAME} 
      PRIVATEFILES ${ARG_PRIVATEFILES}
      MODULEFILES ${ARG_MODULEFILES}
      HEADERUNITFILES ${ARG_HEADERUNITFILES}
      PUBLICFILES ${ARG_PUBLICFILES}
      INTERFACEFILES ${ARG_INTERFACEFILES}
      TESTFILES ${ARG_TESTFILES}
      MAINFILE ${ARG_MAINTESTFILE}
    )
  endif()

  if(BUILD_BENCHMARKS AND ARG_BENCHMARKFILES)
    add_benchmark_target_sources( ${TARGETNAME} 
      PRIVATEFILES ${ARG_PRIVATEFILES}
      MODULEFILES ${ARG_MODULEFILES}
      HEADERUNITFILES ${ARG_HEADERUNITFILES}
      PUBLICFILES ${ARG_PUBLICFILES}
      INTERFACEFILES ${ARG_INTERFACEFILES}
      BENCHMARKFILES ${ARG_BENCHMARKFILES}
      MAINFILE ${ARG_MAINBENCHMARKFILE}
    )
  endif()

endfunction()

function(add_target_link_libraries TARGETNAME)
  set(options)
  set(oneValueArgs)
  set(multiValueArgs TESTLIBS BENCHMARKLIBS PRIVATELIBS PUBLICLIBS INTERFACELIBS)

  cmake_parse_arguments(PARSE_ARGV 1 ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" )

  #message(STATUS "function=${CMAKE_CURRENT_FUNCTION}")
  #message(STATUS "ARGV=${ARGV}")
  #message(STATUS "ARGN=${ARGN}")
  #message(STATUS "TARGETNAME=${TARGETNAME}")
  #message(STATUS "TESTLIBS=${ARG_TESTLIBS}")
  #message(STATUS "BENCHMARKLIBS=${ARG_BENCHMARKLIBS}")
  #message(STATUS "PRIVATELIBS=${ARG_PRIVATELIBS}")
  #message(STATUS "PUBLICLIBS=${ARG_PUBLICLIBS}")
  #message(STATUS "INTERFACELIBS=${ARG_INTERFACELIBS}")
  #message(STATUS "UNPARSED_ARGUMENTS=${ARG_PREFIX_UNPARSED_ARGUMENTS}")
  #message(STATUS "KEYWORDS_MISSING_VALUES=${ARG_KEYWORDS_MISSING_VALUES}")

  target_link_libraries(${TARGETNAME}
    PRIVATE
      ${ARG_PRIVATELIBS}
    PUBLIC
      ${ARG_PUBLICLIBS}
    INTERFACE
      ${ARG_INTERFACELIBS}
  )

  if(BUILD_TESTS)
    add_test_target_link_libraries(${TARGETNAME}
      PRIVATELIBS ${ARG_PRIVATELIBS}
      PUBLICLIBS ${ARG_PUBLICLIBS}
      INTERFACELIBS ${ARG_INTERFACELIBS}
      TESTLIBS ${ARG_TESTLIBS}
    )
  endif()

  if(BUILD_BENCHMARKS)
    add_benchmark_target_link_libraries(${TARGETNAME}
      PRIVATELIBS ${ARG_PRIVATELIBS}
      PUBLICLIBS ${ARG_PUBLICLIBS}
      INTERFACELIBS ${ARG_INTERFACELIBS}
      BENCHMARKLIBS ${ARG_TESTLIBS}
    )
  endif()

endfunction()