include_guard(GLOBAL)

if(EXISTS ${CMAKE_SOURCE_DIR}/vcpkg.json)
    file(REAL_PATH ${CMAKE_TOOLCHAIN_FILE} CMAKE_TOOLCHAIN_FILE EXPAND_TILDE)
    if(NOT EXISTS  ${CMAKE_TOOLCHAIN_FILE})
        message(FATAL_ERROR "CMAKE_TOOLCHAIN_FILE does not exist: CMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}")
    endif()
endif()