name: Benchmarks

on: 
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      buildConfig:
        required: true
        type: string
      configurePreset:
        required: true
        type: string
      buildPreset:
        required: true
        type: string
      testPreset:
        required: true
        type: string
      experimental:
        required: true
        type: boolean

jobs:
  benchamrks:
  
    runs-on: ${{ matrix.config.os }}
    continue-on-error: ${{ matrix.config.experimental }}
    name: ${{ matrix.config.buildPreset }}

    env:
      buildConfigBinDir: "_Out/build/${{ matrix.config.configurePreset }}/_bin/${{ matrix.config.buildConfig }}"
      fullBinDir: "${{ github.workspace }}/_Out/build/${{ matrix.config.configurePreset }}/_bin"
      libDir: "_Out/build/${{ matrix.config.configurePreset }}/_lib"

    steps:
      - name: Foresight Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_API_KEY }}

      - name: Cache Build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.buildConfigBinDir }}
            OpenCppCoverage.config.txt
          key: CacheBuild-${{ github.run_id }}-${{ runner.os }}-${{ matrix.config.configurePreset }}-${{ matrix.config.buildConfig }}

      - name: Run Google Benchmark (${{ runner.os }})
        if: runner.os == 'Windows'
        run: |
          $buildConfigBinDir = "${{ env.buildConfigBinDir }}"
          $benchmarkExe = (Get-ChildItem -Path $buildConfigBinDir -Recurse | Where-Object Name -like *benchmarks*.exe).FullName
          foreach ($exe in $benchmarkExe) {
            Write-Host($exe)
            $exeName = Get-ChildItem $exe | Select-Object -ExpandProperty BaseName
            Write-Host($exeName)
            &$exe --benchmark_out_format=json --benchmark_out=$exeName.json
          }
