name: Cmake build

on: [push, pull_request, release]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            os: windows-latest,
            configurePreset: windows-vs2022,
            buildPreset: windows-vs2022-x64-debug,
            testPreset: windows-vs2022-x64-debug
          }
        - {
            os: windows-latest,
            configurePreset: windows-vs2022,
            buildPreset: windows-vs2022-x64-release,
            testPreset: windows-vs2022-x64-release
          }
        - {
            os: windows-latest,
            configurePreset: windows-vs2022,
            buildPreset: windows-vs2022-x64-shipping,
            testPreset: windows-vs2022-x64-shipping
          }
        - {
            os: ubuntu-latest,
            configurePreset: linux-ninja-multi-config,
            buildPreset: linux-ninja-multi-config-x64-debug,
            testPreset: linux-ninja-multi-config-x64-debug
          }
        - {
            os: ubuntu-latest,
            configurePreset: linux-ninja-multi-config,
            buildPreset: linux-ninja-multi-config-x64-release,
            testPreset: linux-ninja-multi-config-x64-release
          }
        - {
            os: ubuntu-latest,
            configurePreset: linux-ninja-multi-config,
            buildPreset: linux-ninja-multi-config-x64-shipping,
            testPreset: linux-ninja-multi-config-x64-shipping
          }
        


  # include:
  #   - os: windows-latest
  #     buildType: Debug
  #     configurePreset: x64-debug
  #   - os: windows-latest
  #     buildType: Release
  #     configurePreset: x64-release
  #   - os: windows-latest
  #     buildType: Shipping
  #     configurePreset: x64-shipping
    # name: ${{ matrix.buildType }} build on ${{ matrix.os }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v3  
      with:
        lfs: true
        submodules: true

    - name: Cache vcpkg
      id: cache-vcpkg
      uses: actions/cache@v3
      with:
        path: _Out/build/${{ matrix.config.configurePreset }}/vcpkg_installed
        key: ${{ runner.os }}-${{ matrix.config.configurePreset }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}

    - name: Install Ninja-Build
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install ninja-build

    - name: "Set environmental variables"
      run: |
        echo $VCPKG_INSTALLATION_ROOT >> $VCPKG_ROOT

    - name: Cmake Configure
      run: |
        cmake --preset ${{ matrix.config.configurePreset }}

    - name: Cmake Build
      run: |
        cmake --build --preset ${{ matrix.config.buildPreset }}

    - name: CTest
      run: |
        ctest --preset ${{ matrix.config.testPreset }}