name: ci

on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - main
      - dev

jobs:
  build-test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ${{matrix.os}}
    container:
      image:  ${{ matrix.os == 'ubuntu-latest' && 'ghcr.io/monamimani-builds/cpp-devcontainer:a524189b6082de6c08216ef1f3ea2544a9cdf5a4' || '' }}
    strategy:
      fail-fast: false

      # CMake preset name template: "%Platform%-%Compiler%-%Generator%-%BuildType%-%BuildKind%"
      # matrix:
      #   platform: [
      #     {name: Linux, os: ubuntu-latest},
      #     {name: Windows, os: windows-latest }
      #     ]
      #   compiler: [Gcc, Clang, Clang-cl, Msvc]
      #   generator: [{name: Ninja, isMultiConfig: false}]
      #   build_type: [Debug, Release]
      #   #build_kind: [Dev, QA, Profile, Shipping]

      #   exclude: #Becasue they don't make sense or no Cmake preset created.
      #     - platform: {name: Linux}
      #       compiler: Msvc
      #     - platform: {name: Linux}
      #       compiler: Clang-cl
      #     - platform: {name: Windows}
      #       compiler: Clang
      #     - platform: {name: Windows}
      #       compiler: Gcc
      #     # - build_kind: QA
      #     #   build_type: Debug
      #     # - build_kind: Shipping
      #     #   build_type: Debug
      #     # - build_kind: Profile
          
      #   include: # combinasions that are one off
      #     - platform: {name: Linux, os: ubuntu-latest}
      #       compiler: Clang
      #       generator: [{name: NinjaMultiConfig, isMultiConfig: true}]
      #       build_type: Debug
      #       #build_kind: Dev
      #     - platform: {name: Windows, os: windows-latest }
      #       compiler: Msvc
      #       generator: [{name: Vs2022, isMultiConfig: true}]
      #       build_type: Debug
      #       #build_kind: Dev
      #     - platform: {name: Windows, os: windows-latest }
      #       compiler: Msvc
      #       generator: [{name: NinjaMultiConfig, isMultiConfig: true}]
      #       build_type: Debug
      #       #build_kind: Dev

      matrix:
        include:
          - os: ubuntu-latest
            configure-preset: "Linux-Clang-Ninja-Debug"
            build-preset: "Linux-Clang-Ninja-Debug"
          - os: ubuntu-latest
            configure-preset: "Linux-Clang-Ninja-ReleaseWithDebugInfo"
            build-preset: "Linux-Clang-Ninja-ReleaseWithDebugInfo"
          - os: ubuntu-latest
            configure-preset: "Linux-Clang-Ninja-Release"
            build-preset: "Linux-Clang-Ninja-Release"   
          - os: ubuntu-latest
            configure-preset: "Linux-Gcc-Ninja-Debug"
            build-preset: "Linux-Gcc-Ninja-Debug"
          - os: ubuntu-latest
            configure-preset: "Linux-Gcc-Ninja-ReleaseWithDebugInfo"
            build-preset: "Linux-Gcc-Ninja-ReleaseWithDebugInfo"
          - os: ubuntu-latest
            configure-preset: "Linux-Gcc-Ninja-Release"
            build-preset: "Linux-Gcc-Ninja-Release"    
          - os: ubuntu-latest
            configure-preset: "Linux-Clang-NinjaMultiConfig-Debug"
            build-preset: "Linux-Clang-NinjaMultiConfig-Debug"
          - os: ubuntu-latest
            configure-preset: "Linux-Clang-NinjaMultiConfig-ReleaseWithDebugInfo"
            build-preset: "Linux-Clang-NinjaMultiConfig-ReleaseWithDebugInfo"          
          - os: ubuntu-latest
            configure-preset: "Linux-Gcc-NinjaMultiConfig-Debug"
            build-preset: "Linux-Gcc-NinjaMultiConfig-Debug"
          - os: ubuntu-latest
            configure-preset: "Linux-Gcc-NinjaMultiConfig-ReleaseWithDebugInfo"
            build-preset: "Linux-Gcc-NinjaMultiConfig-ReleaseWithDebugInfo"  
          - os: windows-latest
            configure-preset: "Windows-Msvc-Ninja-Debug"
            build-preset: "Windows-Msvc-Ninja-Debug"
          - os: windows-latest
            configure-preset: "Windows-Msvc-Ninja-ReleaseWithDebugInfo"
            build-preset: "Windows-Msvc-Ninja-ReleaseWithDebugInfo"
          - os: windows-latest
            configure-preset: "Windows-Msvc-Ninja-Release"
            build-preset: "Windows-Msvc-Ninja-Release"        
          - os: windows-latest
            configure-preset: "Windows-Msvc-NinjaMultiConfig"
            build-preset: "Windows-Msvc-NinjaMultiConfig-Debug"
          - os: windows-latest
            configure-preset: "Windows-Msvc-NinjaMultiConfig"
            build-preset: "Windows-Msvc-NinjaMultiConfig-ReleaseWithDebugInfo"
          - os: windows-latest
            configure-preset: "Windows-Msvc-Vs2022"
            build-preset: "Windows-Msvc-Vs2022-Debug"
          - os: windows-latest
            configure-preset: "Windows-Msvc-Vs2022"
            build-preset: "Windows-Msvc-Vs2022-ReleaseWithDebugInfo"


    name: ${{matrix.build-preset}}
    # name: ${{matrix.platform.name}}-${{matrix.compiler}}-${{matrix.generator}}-${{matrix.build_type}}
    #-${{matrix.build_kind}}

    #env:
      # CMAKE_PRESET: ${{matrix.platform.name}}-${{matrix.compiler}}-${{matrix.generator}}-${{matrix.build_type}}
      #-${{matrix.build_kind}}

    steps:
    - uses: actions/checkout@v4

    - name: Env variable
      shell: bash
      run: | 
        printenv
        # echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV

    - name: Set ownership
      shell: bash
      run: |
        # this is to fix GIT not liking owner of the checkout dir
        #chown -R $(id -u):$(id -g) $PWD
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Vcpkg Cache
      uses: ./.github/actions/vcpkg_cache

    - name: CPM Cache
      id: cache-cpm
      uses: actions/cache@v4
      with:
        path: _Out/cpm_sources
        key: ${{ runner.os }}-cpm-${{ hashFiles('**/') }}
        restore-keys: |
          ${{ runner.os }}-cpm-

    # - name: Setup Cache
    #   uses: ./.github/actions/setup_cache
    #   with:
    #     compiler: ${{ matrix.compiler }}
    #     build_type: ${{ matrix.build_type }}
    #     packaging_maintainer_mode: false
    #     generator: ${{ matrix.generator }}


    - name: "[Windows] CMake Configure & Build"
      if: runner.os == 'Windows'
      run: |
        & { . Scripts\Build\VsEnvironment.ps1; LaunchVsDevShell }

        cmake --preset ${{matrix.configure-preset}} -DGIT_SHA:STRING=${{ github.sha }}
        cmake --build --preset ${{matrix.build-preset}}

    - name: "[Linux] CMake Configure & Build"
      if: runner.os == 'Linux'
      continue-on-error: true
      run: |
        
        cmake --preset ${{matrix.configure-preset}} -DGIT_SHA:STRING=${{ github.sha }} -DPersonalWorks_ENABLE_CLANG_TIDY=OFF -DPersonalWorks_ENABLE_CPPCHECK=OFF
        cmake --build --preset ${{matrix.build-preset}}

    # - name: Tests
    #   run: |
    #     cmake --build --preset $CMAKE_PRESET
