name: Personalworks

on: [push, pull_request, release]

jobs:
  build-personalworks:  
    uses: ./.github/workflows/personnalworks-build.yml

  tests-personalworks: 
    needs: build-personalworks 
    uses: ./.github/workflows/personnalworks-tests.yml

  benchamrks-personalworks:  
    needs: build-personalworks 
    uses: ./.github/workflows/personnalworks-benchmarks.yml

  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Foresight Collect Workflow Telemetry
      uses: runforesight/foresight-workflow-kit-action@v1
      if: ${{ always() }}
      with:
        api_key: ${{ secrets.FORESIGHT_API_KEY }}

    - uses: actions/checkout@v3  
      with:
        lfs: true
        submodules: true

    - name: Cache Tools Build
      id: cache-tools-build
      uses: actions/cache@v3
      with:
        path: Tools
        key: cache-tools-build-${{ github.run_id }}

    - name: 'Setup Go for SendToMongoDb'
      uses: actions/setup-go@v3
      with:
        check-latest: true
        go-version-file: 'Tools/UploadDataToMongoDb/go.mod'
        cache: true
        cache-dependency-path: 'Tools/UploadDataToMongoDb/go.sum'

    - name: 'Compile UploadDataToMongoDb'
      run: |
        pushd Tools/UploadDataToMongoDb/
        go version
        go build .
        popd


  SSH_Tunnel:
    runs-on: ubuntu-latest
    needs: build-tools

    # Add permissions for gcloud Authentification
    permissions:
      contents: 'read'
      id-token: 'write'

    container:
      image: google/cloud-sdk:alpine
      ports:
      - 27017:27017
      volumes:
      - Tools

    steps:
    - name: Foresight Collect Workflow Telemetry
      uses: runforesight/foresight-workflow-kit-action@v1
      if: ${{ always() }}
      with:
        api_key: ${{ secrets.FORESIGHT_API_KEY }}

    - name: Cache Tools Build
      id: cache-tools-build
      uses: actions/cache@v3
      with:
        path: Tools
        key: cache-tools-build-${{ github.run_id }}

    - id: 'gcloud_auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{secrets.GCLOUD_IAM_WORKLOAD_IDENTITY_PROVIDER}}
        service_account: personalworks-db@tonal-justice-374902.iam.gserviceaccount.com

    - name: 'SSH Tunnel & SendToMongoDb'
      run: |        
        $(gcloud info --format="value(basic.python_location)") -m pip install numpy

        gcloud config set auth/impersonate_service_account personalworks-db@tonal-justice-374902.iam.gserviceaccount.com
        # gcloud info
        # gcloud compute config-ssh --quiet --verbosity=debug
        # gcloud compute config-ssh --quiet

        # netsh advfirewall firewall add rule name="Open mongod port 27017" dir=in action=allow protocol=TCP localport=27017

        # ssh mongodb-personalworks-servers-vm-0.us-east1-b.tonal-justice-374902 -vvv -fNT -E ssh.log -L 27017:localhost:27017

        # autossh -M 0 -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -o "User=personalworks-db_tonal-justice-374902_iam_gserviceaccount_com" -N -T -L 27017:localhost:27017 mongodb-personalworks-servers-vm-0.us-east1-b.tonal-justice-374902 &

        # $sshTunnelJob = Start-Job -Name SshTunnelJob -ScriptBlock { ssh -o "User=personalworks-db_tonal-justice-374902_iam_gserviceaccount_com" mongodb-personalworks-servers-vm-0.us-east1-b.tonal-justice-374902 -vvv -fNT -L 27017:0.0.0.0:27017}
        # ssh -o "User=personalworks-db_tonal-justice-374902_iam_gserviceaccount_com" mongodb-personalworks-servers-vm-0.us-east1-b.tonal-justice-374902 -v -fNT -L 27017:localhost:27017

        # $sshTunnelJob = Start-Job -Name SshTunnelJob -ScriptBlock { gcloud compute ssh ${{secrets.GCE_INSTANCE_NAME}} --zone us-east1-b --tunnel-through-iap --verbosity=debug --ssh-flag="-T -L 27017:localhost:27017"}
        # gcloud compute ssh ${{secrets.GCE_INSTANCE_NAME}} --quiet --zone us-east1-b --tunnel-through-iap --verbosity=debug --ssh-flag="-o ExitOnForwardFailure=yes -fNT -L 27017:localhost:27017"
        gcloud compute ssh ${{secrets.GCE_INSTANCE_NAME}} --quiet --zone us-east1-b --tunnel-through-iap --ssh-flag="-fNT -L 27017:localhost:27017"

        cd Tools/UploadDataToMongoDb/
        ./SendToMongoDb
        
        gcloud config unset auth/impersonate_service_account
        gcloud compute config-ssh --remove

  Cleanup:
    runs-on: ubuntu-latest
    needs: [build-personalworks, tests-personalworks, benchamrks-personalworks, SSH_Tunnel]
    if: ${{ always() }}

    steps:
    - name: Foresight Collect Workflow Telemetry
      uses: runforesight/foresight-workflow-kit-action@v1
      if: ${{ always() }}
      with:
        api_key: ${{ secrets.FORESIGHT_API_KEY }}

    - uses: actions/checkout@v3 

    - name: 'Clean caches'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |        
        gh extension install actions/gh-actions-cache

        gh actions-cache delete cache-tools-build-${{ github.run_id }} --confirm