name: PersonalWorks Build

on: workflow_call

jobs:
  build:

    strategy:
        matrix:
          platform:
            - os: windows-latest
              genertor: windows-vs2022
              experimental: false
            - os: ubuntu-latest
              genertor: linux-ninja-multi-config
              experimental: true
          architecture: [x64]
          buildConfig: [
            { 
              name: debug,
              optimization: debug
            },
            { 
              name: release,
              optimization: relWithDebInfo
            },
            { 
              name: shipping,
              optimization: release
            },]
          


    # strategy:
    #   fail-fast: false
    #   matrix:
    #     config:
    #     - {
    #         os: windows-latest,
    #         buildConfig: debug,
    #         configurePreset: windows-vs2022,
    #         buildPreset: windows-vs2022-x64-debug,
    #         testPreset: windows-vs2022-x64-debug,
    #         experimental: false
    #       }
    #     - {
    #         os: windows-latest,
    #         buildConfig: relWithDebInfo,
    #         configurePreset: windows-vs2022,
    #         buildPreset: windows-vs2022-x64-release,
    #         testPreset: windows-vs2022-x64-release,
    #         experimental: false
    #       }
    #     - {
    #         os: windows-latest,
    #         buildConfig: release,
    #         configurePreset: windows-vs2022,
    #         buildPreset: windows-vs2022-x64-shipping,
    #         testPreset: windows-vs2022-x64-shipping,
    #         experimental: false
    #       }
    #     - {
    #         os: ubuntu-latest,
    #         buildConfig: debug,
    #         configurePreset: linux-ninja-multi-config,
    #         buildPreset: linux-ninja-multi-config-x64-debug,
    #         testPreset: linux-ninja-multi-config-x64-debug,
    #         experimental: true
    #       }
    #     - {
    #         os: ubuntu-latest,
    #         buildConfig: relWithDebInfo,
    #         configurePreset: linux-ninja-multi-config,
    #         buildPreset: linux-ninja-multi-config-x64-release,
    #         testPreset: linux-ninja-multi-config-x64-release,
    #         experimental: true
    #       }
    #     - {
    #         os: ubuntu-latest,
    #         buildConfig: release,
    #         configurePreset: linux-ninja-multi-config,
    #         buildPreset: linux-ninja-multi-config-x64-shipping,
    #         testPreset: linux-ninja-multi-config-x64-shipping,
    #         experimental: true
    #       }

    runs-on: ${{ matrix.platform.os }}
    continue-on-error: ${{ matrix.platform.experimental }}
    name: ${{ matrix.platform.genertor }}-${{ matrix.architecture }}-${{ matrix.buildConfig.name }}

    env:
      configurePreset: ${{ matrix.platform.genertor }}
      buildConfig: ${{ matrix.buildConfig.optimization }}
      buildPreset: ${{ matrix.platform.genertor }}-${{ matrix.architecture }}-${{ matrix.buildConfig.name }}
      testPreset: ${{ matrix.platform.genertor }}-${{ matrix.architecture }}-${{ matrix.buildConfig.name }}

      buildConfigBinDir: "_Out/build/${{ matrix.platform.genertor }}/_bin/${{ matrix.buildConfig.optimization }}"
      fullBinDir: "${{ github.workspace }}/_Out/build/${{ matrix.config.configurePreset }}/_bin"
      libDir: "_Out/build/${{ matrix.config.configurePreset }}/_lib"

    steps:
      - name: Foresight Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_API_KEY }}

      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true

      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: _Out/build/vcpkg_installed
          key: ${{ runner.os }}-${{ env.configurePreset }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}

      - name: Set environmental variables
        shell: bash
        run: |
          # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path
          echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV

      - name: Install Linux packages
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install gcc-11 g++-11
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11
          sudo apt-get install ninja-build

      - name: Cmake Configure
        run: |
          cmake --preset ${{ env.configurePreset }}

      - name: Cmake Build
        if: runner.os == 'Windows'
        run: |
          cmake --build --preset ${{ env.buildPreset }}

      - name: Cache Build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.buildConfigBinDir }}
            OpenCppCoverage.config.txt
          key: CacheBuild-${{ github.run_id }}-${{ runner.os }}-${{ matrix.config.configurePreset }}-${{ matrix.config.buildConfig }}
          restore-keys: CacheBuild

      - name: Upload Build Artifacts ${{ matrix.config.buildConfig }}
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{github.workflow}}-${{github.job}}-${{ env.configurePreset }}-${{ env.buildConfig }}-Build
          path: |
            _Out/build/${{ env.configurePreset }}/_bin/${{ env.buildConfig }}
            _Out/build/${{ env.configurePreset }}/_lib/${{ env.buildConfig }}