name: PersonalWorks Benchmarks

on: workflow_call

jobs:
  benchamrks-personalwork:
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            os: windows-latest,
            buildConfig: debug,
            configurePreset: windows-vs2022,
            buildPreset: windows-vs2022-x64-debug,
            testPreset: windows-vs2022-x64-debug,
            experimental: false
          }
        - {
            os: windows-latest,
            buildConfig: relWithDebInfo,
            configurePreset: windows-vs2022,
            buildPreset: windows-vs2022-x64-release,
            testPreset: windows-vs2022-x64-release,
            experimental: false
          }
        - {
            os: windows-latest,
            buildConfig: release,
            configurePreset: windows-vs2022,
            buildPreset: windows-vs2022-x64-shipping,
            testPreset: windows-vs2022-x64-shipping,
            experimental: false
          }
        - {
            os: ubuntu-latest,
            buildConfig: debug,
            configurePreset: linux-ninja-multi-config,
            buildPreset: linux-ninja-multi-config-x64-debug,
            testPreset: linux-ninja-multi-config-x64-debug,
            experimental: true
          }
        - {
            os: ubuntu-latest,
            buildConfig: relWithDebInfo,
            configurePreset: linux-ninja-multi-config,
            buildPreset: linux-ninja-multi-config-x64-release,
            testPreset: linux-ninja-multi-config-x64-release,
            experimental: true
          }
        - {
            os: ubuntu-latest,
            buildConfig: release,
            configurePreset: linux-ninja-multi-config,
            buildPreset: linux-ninja-multi-config-x64-shipping,
            testPreset: linux-ninja-multi-config-x64-shipping,
            experimental: true
          }

    runs-on: ${{ matrix.config.os }}
    continue-on-error: ${{ matrix.config.experimental }}
    name: ${{ matrix.config.buildPreset }}

    env:
      buildConfigBinDir: "_Out/build/${{ matrix.config.configurePreset }}/_bin/${{ matrix.config.buildConfig }}"
      fullBinDir: "${{ github.workspace }}/_Out/build/${{ matrix.config.configurePreset }}/_bin"
      libDir: "_Out/build/${{ matrix.config.configurePreset }}/_lib"

    steps:
      - name: Foresight Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_API_KEY }}

      - name: Cache Build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ${{ env.buildConfigBinDir }}
          key: CacheBuild-${{ runner.os }}-${{ matrix.config.configurePreset }}-${{ matrix.config.buildConfig }}-${{ github.run_id }}

      - name: Run Google Benchmark (${{ runner.os }})
        run: |
          $buildConfigBinDir = "${{ env.buildConfigBinDir }}"
          $benchmarkExe = (Get-ChildItem -Path $buildConfigBinDir -Recurse | Where-Object Name -like *benchmarks*.exe).FullName
          foreach ($exe in $benchmarkExe) {
            Write-Host($exe)
            $exeName = Get-ChildItem $exe | Select-Object -ExpandProperty BaseName
            Write-Host($exeName)
            &$exe --benchmark_out_format=json --benchmark_out=$exeName.json
          }
