on: 
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      buildConfig:
        required: true
        type: string
      configurePreset:
        required: true
        type: string
      buildPreset:
        required: true
        type: string
      testPreset:
        required: true
        type: string
      experimental:
        required: true
        type: boolean

jobs:
  build:
    runs-on: ${{ inputs.os }}
    continue-on-error: ${{ inputs.experimental }}
    steps:
    - name: Foresight Collect Workflow Telemetry
      uses: runforesight/foresight-workflow-kit-action@v1
      if: ${{ always() }}
      with:
        api_key: ${{ secrets.FORESIGHT_API_KEY }}

    - uses: actions/checkout@v3
      with:
        lfs: true
        submodules: true

    - uses: ./.github/actions/build
      with:
        buildConfig: ${{ inputs.buildConfig }}
        configurePreset: ${{ inputs.configurePreset }}
        buildPreset: ${{ inputs.buildPreset }}

  tests:
    needs: build
    runs-on: ${{ inputs.os }}
    continue-on-error: ${{ inputs.experimental }}
    steps:
    - name: Foresight Collect Workflow Telemetry
      uses: runforesight/foresight-workflow-kit-action@v1
      if: ${{ always() }}
      with:
        api_key: ${{ secrets.FORESIGHT_API_KEY }}
    - uses: ./.github/actions/tests
      with:
        buildConfig: ${{ inputs.buildConfig }}
        configurePreset: ${{ inputs.configurePreset }}
        testPreset: ${{ inputs.testPreset }}

  benchmarks:
    needs: build
    runs-on: ${{ inputs.os }}
    continue-on-error: ${{ inputs.experimental }}
    steps:
    - name: Foresight Collect Workflow Telemetry
      uses: runforesight/foresight-workflow-kit-action@v1
      if: ${{ always() }}
      with:
        api_key: ${{ secrets.FORESIGHT_API_KEY }}
    - uses: ./.github/actions/benchmarks
      with:
        buildConfig: ${{ inputs.buildConfig }}
        configurePreset: ${{ inputs.configurePreset }}
